function showToast(message) { const t = document.getElementById("toast"); if (!t) return; t.textContent = message; t.classList.add("show"); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => t.classList.remove("show"), 2600) }
function searchFromHero() { const q = document.getElementById("heroSearch").value.trim(); window.location.href = "jasa.html" + (q ? "?q=" + encodeURIComponent(q) : "") }
function togglePassword(id) { const el = document.getElementById(id); el.type = el.type === "password" ? "text" : "password" }
function fakeAuth(e, msg) { e.preventDefault(); showToast(msg); setTimeout(() => window.location.href = "index.html", 900) }
function placeOrder() { showToast("Order berhasil dibuat (demo). Fitur pembayaran masuk di tahap backend.") }
function renderServices(list) { const box = document.getElementById("serviceResults"); if (!box) return; document.getElementById("resultCount").textContent = `${list.length} jasa ditemukan`; if (!list.length) { box.innerHTML = '<div class="empty">Tidak ada jasa yang cocok. Filter memang kadang punya jiwa sendiri.</div>'; return } box.innerHTML = list.map(s => `<article class="service-card"><div class="service-cover ${s.cover}"><span>${s.category.toUpperCase()}<br>CREATIVE</span><i>${s.category === "Programming" ? "⌘" : s.category === "Video" ? "◒" : "✦"}</i></div><div class="service-body"><div class="service-cat">${s.category.toUpperCase()}</div><h3>${s.title}</h3><div class="seller"><span class="avatar avatar-${s.color}">${s.initials}</span><span><b>${s.seller}</b><small>★ ${s.rating} · ${s.orders} order</small></span></div><div class="service-foot"><span>Mulai dari <b>Rp${s.price.toLocaleString("id-ID")}</b></span><a href="detail.html">Lihat →</a></div></div></article>`).join("") }
function getQuery() { return new URLSearchParams(window.location.search).get("q") || "" }
function filterServices() { if (typeof services === "undefined") return; const q = (document.getElementById("searchInput")?.value || "").toLowerCase(); const cats = [...document.querySelectorAll(".filters input[type=checkbox]:checked")].map(x => x.value); const min = Number(document.getElementById("minPrice")?.value || 0); const max = Number(document.getElementById("maxPrice")?.value || Infinity); const rating = Number(document.getElementById("ratingFilter")?.value || 0); let list = services.filter(s => (!q || `${s.title} ${s.category} ${s.seller}`.toLowerCase().includes(q)) && (!cats.length || cats.includes(s.category)) && s.price >= min && s.price <= max && s.rating >= rating); renderServices(list) }
function sortServices() { if (typeof services === "undefined") return; const select = document.getElementById("sortSelect"); const q = (document.getElementById("searchInput")?.value || "").toLowerCase(); let list = services.filter(s => !q || `${s.title} ${s.category} ${s.seller}`.toLowerCase().includes(q)); if (select.value === "price") list.sort((a, b) => a.price - b.price); if (select.value === "rating") list.sort((a, b) => b.rating - a.rating); renderServices(list) }
function resetFilters() { document.querySelectorAll(".filters input[type=checkbox]").forEach(x => x.checked = false); document.getElementById("minPrice").value = ""; document.getElementById("maxPrice").value = ""; document.getElementById("ratingFilter").value = "0"; document.getElementById("searchInput").value = ""; renderServices(services) }
document.addEventListener("DOMContentLoaded", () => { if (typeof services !== "undefined" && document.getElementById("serviceResults")) { const q = getQuery(); document.getElementById("searchInput").value = q; filterServices() } })
